name = "ILBE Assault Pack (TFAR) - Rewrite";
picture = "";
actionName = "Website";
action = "https://discord.gg/QPEjKvV";
description = "Discord: https://discord.gg/QPEjKvV";
logo = "";
logoOver = "";
tooltip = "ILBE Assault Pack (TFAR) - Rewrite";
tooltipOwned = "ILBE Assault Pack (TFAR) - Rewrite Owned";
overview = "";
author = "Grezvany13";
overviewPicture = "";
overviewText = "ILBE Assault Pack (TFAR) - Rewrite";
overviewFootnote = "<br /><br /><t color='#999999'>This work is licensed under ARMA PUBLIC LICENSE SHARE ALIKE (APL-SA).<t />";
